version: '3.6'

services:

  engine:
    container_name: 'rwid-scraper-source'
    build:
      context: ./
      dockerfile: Dockerfile-prod
    expose:
      - 9999
    environment:
      - FLASK_APP=manage
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://amazinguser:amazingPassword@engine-db:5432/rwid_scraper_source
      - DATABASE_TEST_URL=postgres://amazinguser:amazingPassword@engine-db:5432/rwid_scraper_source_test
    depends_on:
      - engine-db

  engine-db:
    container_name: 'rwid-scraper-source-db'
    build:
      context: services/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=amazinguser
      - POSTGRES_PASSWORD=amazingPassword

  nginx:
    container_name: 'rwid-scraper-source-nginx'
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 9999:80
    depends_on:
      - engine
